name: cybrbrother
favicon: null
layout_spectrum: 0.33108
typography_spectrum: 0.5057723114732653
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.625
  lightness: 0.474130965070799
  saturation: 0.7275638803839684
  rhythmicContrast: 0.2564447277691215
purpose: []
