favicon: null
name: cybrbrother
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.3655914
  lightness: 0.218638
  brandStrength: 0.625
  brandColors: []
  rhythmicContrast: 0.5089605
typography_spectrum: 0.5057723114732653
layout_spectrum: 0.5089605
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
