name: cybrbrother
favicon: null
layout_spectrum: 0.5089605
typography_spectrum: 0.5057723114732653
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: cyb3r br0th3r
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.625
  lightness: 0.218638
  saturation: 0.3655914
  rhythmicContrast: 0.5089605
purpose: []
